name: m4d_template_sample
description: Material4Dart (m4d) 'm4d_template' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/m4d_template

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  uuid: any
  
  m4d_template:
    path: ../..

  m4d_core: '>=0.2.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_core

  m4d_animation: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_animation

  m4d_components: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_components

  m4d_flux: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_flux

  m4d_form: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_form

  m4d_directive: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_directive

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: any
  
