name: m4d_template
description: Material Design 4 Dart - Template-based components
version: 0.2.3
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/m4d_template

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.15.0
  platform_detect: ^1.3.0

  validate: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

  path: ^1.4.0

  m4d_core: '>=0.1.0 <1.0.0'
    # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_core

  m4d_directive: '>=0.1.0 <1.0.0'
     # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_directive

  m4d_flux: '>=0.1.0 <1.0.0'
    # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_flux

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
